# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://dosk.win
date_format: "ordinal"
title: "Dosk 技术站"
subtitle: "SpringHack 的无名技术小站"
description: "SpringHack 的无名技术小站"
keywords: SpringHack, Dosk
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: SpringHack
organization: 
organization_url: 
github_username: springhack
location: Beijing, China
email: springhack@live.cn

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页
  -
    href: /categories/
    label: 分类
  -
    href: /archives/
    label: 归档
  -
    href: /links/
    label: 链接
  -
    href: /old_posts/
    label: 旧闻
  - href: /open-source/
    label: 仓库
  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 10
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
    - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: springhack/springhack.github.io

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk

gitalk:
  clientID: '63125e6057f210f8095c'
  clientSecret: 'e0a6c16cb45c54eb578e6fead8a87cf70b0471e0'
  repo: 'SpringHack'
  owner: 'springhack'

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    fulltext: false
    limit: 10

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: "UA-75374967-1"
